version: '2'
services:
  jhipstertest-app:
    image: jhipstertest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipstertest-mssql:1433;database=jhipstertest
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstertest-mssql:
    extends:
      file: mssql.yml
      service: jhipstertest-mssql
